# Generated by Django 5.0.7 on 2024-07-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_comment_author_id_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='course_id',
        ),
    ]
